"""make_user_email_username_nullable

Revision ID: 93ce6ec0027d
Revises: 5ea4fba4d374
Create Date: 2025-05-28 10:26:36.266367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93ce6ec0027d'
down_revision: Union[str, None] = '5ea4fba4d374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_prompt_user_id', 'prompts', ['user_id'], unique=False)
    op.create_index('ix_user_api_key_user_id_llm_provider', 'user_api_keys', ['user_id', 'llm_provider'], unique=True)
    op.alter_column('userdb', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('userdb_email_key', 'userdb', type_='unique')
    op.drop_constraint('userdb_username_key', 'userdb', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('userdb_username_key', 'userdb', ['username'])
    op.create_unique_constraint('userdb_email_key', 'userdb', ['email'])
    op.alter_column('userdb', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index('ix_user_api_key_user_id_llm_provider', table_name='user_api_keys')
    op.drop_index('ix_prompt_user_id', table_name='prompts')
    # ### end Alembic commands ###
