"""add_has_seen_paywall_modal_to_user

Revision ID: cbd0a67847a1
Revises: 93ce6ec0027d
Create Date: 2025-05-29 01:50:53.057919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbd0a67847a1'
down_revision: Union[str, None] = '93ce6ec0027d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add column as nullable first
    op.add_column('userdb', sa.Column('has_seen_paywall_modal', sa.Boolean(), nullable=True))
    
    # Step 2: Update all existing users to have default value of False
    op.execute("UPDATE userdb SET has_seen_paywall_modal = false WHERE has_seen_paywall_modal IS NULL")
    
    # Step 3: Now make the column NOT NULL since all existing rows have values
    op.alter_column('userdb', 'has_seen_paywall_modal', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userdb', 'has_seen_paywall_modal')
    # ### end Alembic commands ###
